#:schema node_modules/wrangler/config-schema.json
name = "octomailer"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_USERNAME = ""
GITHUB_REPO = ""
GITHUB_TOKEN = ""
